import type { Metadata } from "next";
import { Antonio, Geist, Geist_Mono, Lobster, Nunito } from "next/font/google";
import "./globals.css";
import ScrollSmootherProvider from "@/providers/lenis";
import ClientLayout from "@/providers/ClientLayout";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const antonio = Antonio({
  variable: "--font-antonio",
  subsets: ["latin"],
});
const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});
const lobster = Lobster({
  variable: "--font-lobster",
  subsets: ["latin"],
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${nunito.variable} ${antonio.variable} ${geistMono.variable} ${lobster.variable}  antialiased`}
      >
        <ClientLayout>
          <Navbar />
          <ScrollSmootherProvider>
            {children}
          </ScrollSmootherProvider>
        </ClientLayout>
      </body>
    </html>
  );
}
